name: build pages
on:
  push:
    branches: master
  pull_request:
jobs:
  build:
    deploy: &deploy_base
      uses: netlify/actions/cli@master
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: Install Dependencies
        run: npm ci --production
      - name: Build pages
        run: npm run build
      - name: Deploy draft
        if: github.event_name == 'pull_request'
        <<: *deploy_base
        with:
          args: deploy --dir=dist
      - name: Deploy production
        if: github.ref == 'refs/heads/master'
        <<: *deploy_base
        with:
          args: deploy --dir=dist --prod
